[General]
Font="Plus Jakarta Sans"
FontSize="12"
HourFormat="HH:mm"
DateFormat="dddd d MMMM"

Background="backgrounds/sodalite.mp4"

AnimationDuration="300"
AnimationEasing="OutQuart"

DateTextColor="#EDF1F7"
TimeTextColor="#FAFBFD"

InputFieldBackgroundColor="#55AEB8CB"
InputFieldTextColor="#F8FAFD"
PlaceholderTextColor="#D5DBE6"

LoginButtonTextColor="#F7F9FD"
LoginButtonBackgroundColor="#647FA8"

SystemButtonsIconsColor="#5F7294"
EnvironmentButtonTextColor="#5F7294"

DropdownTextColor="#EFF2F8"
DropdownBackgroundColor="#1D2942"
DropdownSelectedBackgroundColor="#5876A2"

HoverLoginButtonBackgroundColor="#718CB3"
HoverSystemButtonsIconsColor="#7188AD"
HoverEnvironmentButtonTextColor="#7188AD"

Blur="0.03"
FormPosition="left"