[General]
Font="Plus Jakarta Sans"
FontSize="12"
HourFormat="HH:mm"
DateFormat="dddd d MMMM"

Background="backgrounds/blush.jpg"

AnimationDuration="300"
AnimationEasing="OutQuart"

DateTextColor="#d8c3c6"
TimeTextColor="#f3e9ea"

InputFieldBackgroundColor="#402a1317"
InputFieldTextColor="#f3e9ea"
PlaceholderTextColor="#a78f93"

LoginButtonTextColor="#160809"
LoginButtonBackgroundColor="#b8696c"

SystemButtonsIconsColor="#d8c3c6"
EnvironmentButtonTextColor="#d8c3c6"

DropdownTextColor="#e6d6d8"
DropdownBackgroundColor="#160a0d"
DropdownSelectedBackgroundColor="#b8696c"

HoverLoginButtonBackgroundColor="#cc7f84"
HoverSystemButtonsIconsColor="#cc7f84"
HoverEnvironmentButtonTextColor="#cc7f84"

Blur="0.2"
FormPosition="center"
