[General]
Font="Plus Jakarta Sans"
FontSize="12"
HourFormat="HH:mm"
DateFormat="dddd d MMMM"

Background="backgrounds/blush.jpg"

AnimationDuration="300"
AnimationEasing="OutQuart"

AutoFingerprintOnLoad=true

DateTextColor="#d8c3c6"
TimeTextColor="#f3e9ea"

FormBackgroundColor="#11080a"

LoginFieldBackgroundColor="#2a1317"
PasswordFieldBackgroundColor="#2a1317"

LoginFieldTextColor="#f3e9ea"
PasswordFieldTextColor="#f3e9ea"

PlaceholderTextColor="#a78f93"

LoginButtonTextColor="#160809"
LoginButtonBackgroundColor="#b8696c"

SystemButtonsIconsColor="#d8c3c6"
EnvironmentButtonTextColor="#d8c3c6"

DropdownTextColor="#e6d6d8"
DropdownSelectedTextColor="#160809"
DropdownBackgroundColor="#160a0d"
DropdownSelectedBackgroundColor="#b8696c"
DropdownBorderColor="#3a1a1f"
DropdownSelectedBorderColor="#d7a1a5"

HoverLoginButtonBackgroundColor="#cc7f84"
HoverSystemButtonsIconsColor="#cc7f84"
HoverEnvironmentButtonTextColor="#cc7f84"

Blur="0.2"
FormPosition="center"
