[General]
Font="Plus Jakarta Sans"
FontSize="12"
HourFormat="HH:mm"
DateFormat="dddd d MMMM"

Background="backgrounds/carnelian.png"

AnimationDuration="300"
AnimationEasing="OutQuart"

DateTextColor="#d7a49a"
TimeTextColor="#f2d0c8"

InputFieldBackgroundColor="#70140b0a"
InputFieldTextColor="#f4ddd7"
PlaceholderTextColor="#a9756b"

LoginButtonTextColor="#090302"
LoginButtonBackgroundColor="#d85843"

SystemButtonsIconsColor="#e5b8ae"
EnvironmentButtonTextColor="#e5b8ae"

DropdownTextColor="#f4ddd7"
DropdownBackgroundColor="#0b0605"
DropdownSelectedBackgroundColor="#b94233"

HoverLoginButtonBackgroundColor="#ee735b"
HoverSystemButtonsIconsColor="#ee735b"
HoverEnvironmentButtonTextColor="#ee735b"

Blur="0.05"
FormPosition="center"