[General]
Font="Plus Jakarta Sans"
FontSize="12"
HourFormat="HH:mm"
DateFormat="dddd d MMMM"

Background="backgrounds/cinder.mp4"

AnimationDuration="300"
AnimationEasing="OutQuart"

AutoFingerprintOnLoad=true

DateTextColor="#e4b2a3"
TimeTextColor="#ffd0bf"

FormBackgroundColor="#070304"

LoginFieldBackgroundColor="#16090a"
PasswordFieldBackgroundColor="#16090a"

LoginFieldTextColor="#fdc7b7"
PasswordFieldTextColor="#fdc7b7"

PlaceholderTextColor="#b77e74"

LoginButtonTextColor="#070304"
LoginButtonBackgroundColor="#f16f1c"

SystemButtonsIconsColor="#f3c4aa"
EnvironmentButtonTextColor="#f3c4aa"

DropdownTextColor="#fff0df"
DropdownSelectedTextColor="#070304"
DropdownBackgroundColor="#0b0505"
DropdownSelectedBackgroundColor="#f16f1c"
DropdownBorderColor="#5d2815"
DropdownSelectedBorderColor="#fdb039"

HoverLoginButtonBackgroundColor="#fdb039"
HoverSystemButtonsIconsColor="#fb8627"
HoverEnvironmentButtonTextColor="#fb8627"

Blur="0.0"
FormPosition="left"