[General]
Font="Plus Jakarta Sans"
FontSize="12"
HourFormat="HH:mm"
DateFormat="dddd d MMMM"

Background="backgrounds/gilded.jpg"

AnimationDuration="300"
AnimationEasing="OutQuart"

DateTextColor="#cbbfb0"
TimeTextColor="#e8e0d3"

InputFieldBackgroundColor="#40e6a84a"
InputFieldTextColor="#e8e0d3"
PlaceholderTextColor="#8f8a7d"

LoginButtonTextColor="#0b0d0a"
LoginButtonBackgroundColor="#ca8732"

SystemButtonsIconsColor="#e8e0d3"
EnvironmentButtonTextColor="#e8e0d3"

DropdownTextColor="#e8e0d3"
DropdownBackgroundColor="#14201a"
DropdownSelectedBackgroundColor="#ca8732"

HoverLoginButtonBackgroundColor="#d19a45"
HoverSystemButtonsIconsColor="#ca8732"
HoverEnvironmentButtonTextColor="#ca8732"

Blur="0.0"
FormPosition="left"
