[General]
Font="Plus Jakarta Sans"
FontSize="12"
HourFormat="HH:mm"
DateFormat="dddd d MMMM"

Background="backgrounds/gilded.jpg"

AnimationDuration="300"
AnimationEasing="OutQuart"

AutoFingerprintOnLoad=true

DateTextColor="#cbbfb0"
TimeTextColor="#e8e0d3"

FormBackgroundColor="#1a221b"
LoginFieldBackgroundColor="#e6a84a"
PasswordFieldBackgroundColor="#e6a84a"

LoginFieldTextColor="#e8e0d3"
PasswordFieldTextColor="#e8e0d3"
PlaceholderTextColor="#8f8a7d"

LoginButtonTextColor="#0b0d0a"
LoginButtonBackgroundColor="#ca8732"

SystemButtonsIconsColor="#e8e0d3"
EnvironmentButtonTextColor="#e8e0d3"

DropdownTextColor="#e8e0d3"
DropdownSelectedTextColor="#0b0d0a"
DropdownBackgroundColor="#14201a"
DropdownSelectedBackgroundColor="#ca8732"
DropdownBorderColor="#2b3327"
DropdownSelectedBorderColor="#d19a45"

HoverLoginButtonBackgroundColor="#d19a45"
HoverSystemButtonsIconsColor="#ca8732"
HoverEnvironmentButtonTextColor="#ca8732"

Blur="0.0"
FormPosition="left"

