[General]
Font="Plus Jakarta Sans"
FontSize="12"
HourFormat="HH:mm"
DateFormat="dddd d MMMM"

Background="backgrounds/kyanite.jpg"

AnimationDuration="300"
AnimationEasing="OutQuart"

DateTextColor="#7FA8BA"
TimeTextColor="#C2DCE8"

InputFieldBackgroundColor="#40205870"
InputFieldTextColor="#D6EAF2"
PlaceholderTextColor="#7DA4B5"

LoginButtonTextColor="#061014"
LoginButtonBackgroundColor="#16789A"

SystemButtonsIconsColor="#A8C6D3"
EnvironmentButtonTextColor="#A8C6D3"

DropdownTextColor="#D6EAF2"
DropdownBackgroundColor="#0A1B22"
DropdownSelectedBackgroundColor="#16789A"

HoverLoginButtonBackgroundColor="#2492B4"
HoverSystemButtonsIconsColor="#2492B4"
HoverEnvironmentButtonTextColor="#2492B4"

Blur="0.1"
FormPosition="left"
