[General]
Font="Plus Jakarta Sans"
FontSize="12"
HourFormat="HH:mm"
DateFormat="dddd d MMMM"

Background="backgrounds/malachite.jpg"

AnimationDuration="300"
AnimationEasing="OutQuart"

DateTextColor="#bdf5ef"
TimeTextColor="#eafffb"

InputFieldBackgroundColor="#40039687"
InputFieldTextColor="#eafffb"
PlaceholderTextColor="#7fbcb3"

LoginButtonTextColor="#00140e"
LoginButtonBackgroundColor="#009a93"

SystemButtonsIconsColor="#bdf5ef"
EnvironmentButtonTextColor="#bdf5ef"

DropdownTextColor="#bdf5ef"
DropdownBackgroundColor="#001a12"
DropdownSelectedBackgroundColor="#009a93"

HoverLoginButtonBackgroundColor="#19b3ae"
HoverSystemButtonsIconsColor="#19b3ae"
HoverEnvironmentButtonTextColor="#19b3ae"

Blur="0.05"
FormPosition="center"
