[General]
Font="Plus Jakarta Sans"
FontSize="13"
HourFormat="HH:mm"
DateFormat="dddd d MMMM"

Background="backgrounds/onyx.jpeg"

AnimationDuration="300"
AnimationEasing="OutQuart"

DateTextColor="#aaa9ad"
TimeTextColor="#eeeeef"

InputFieldBackgroundColor="#80605f63"
InputFieldTextColor="#f1f1f2"
PlaceholderTextColor="#9a999e"

LoginButtonTextColor="#09090a"
LoginButtonBackgroundColor="#a7a6aa"

SystemButtonsIconsColor="#d1d0d3"
EnvironmentButtonTextColor="#d1d0d3"

DropdownTextColor="#eeeeef"
DropdownBackgroundColor="#111113"
DropdownSelectedBackgroundColor="#69686d"

HoverLoginButtonBackgroundColor="#c2c1c5"
HoverSystemButtonsIconsColor="#eeeeef"
HoverEnvironmentButtonTextColor="#eeeeef"

Blur="0.0"
FormPosition="center"