[General]
Font="Plus Jakarta Sans"
FontSize="13"
HourFormat="hh:mm"
DateFormat="dddd, d MMMM"

Background="backgrounds/sable.jpg"

AnimationDuration="300"
AnimationEasing="OutQuart"

DateTextColor="#d8c4b3"
TimeTextColor="#f3e8dc"

InputFieldBackgroundColor="#70402a1d"
InputFieldTextColor="#ddcec1"
PlaceholderTextColor="#9d897d"

LoginButtonTextColor="#0a0706"
LoginButtonBackgroundColor="#d0ab86"

SystemButtonsIconsColor="#dbc7b5"
EnvironmentButtonTextColor="#dbc7b5"

DropdownTextColor="#f3e8dc"
DropdownBackgroundColor="#302119"
DropdownSelectedBackgroundColor="#a27a58"

HoverLoginButtonBackgroundColor="#e0bc97"
HoverSystemButtonsIconsColor="#d7af89"
HoverEnvironmentButtonTextColor="#d7af89"

Blur="0.02"
FormPosition="center"