[General]
Font="Plus Jakarta Sans"
FontSize="12"
HourFormat="HH:mm"
DateFormat="dddd d MMMM"

Background="backgrounds/sakura.jpg"

AnimationDuration="300"
AnimationEasing="OutQuart"

DateTextColor="#ffffff"
TimeTextColor="#ffffff"

InputFieldBackgroundColor="#400b0d12"
InputFieldTextColor="#e0e0e0"
PlaceholderTextColor="#9aa0a6"

LoginButtonTextColor="#ffffff"
LoginButtonBackgroundColor="#282a32"

SystemButtonsIconsColor="#F8F8F2"
EnvironmentButtonTextColor="#F8F8F2"

DropdownTextColor="#ffffff"
DropdownBackgroundColor="#21222C"
DropdownSelectedBackgroundColor="#343746"

HoverLoginButtonBackgroundColor="#3a3c44"
HoverSystemButtonsIconsColor="#C0C0C0"
HoverEnvironmentButtonTextColor="#C0C0C0"

Blur="0.4"
FormPosition="left"
