[General]
Font="Plus Jakarta Sans"
FontSize="12"
HourFormat="HH:mm"
DateFormat="dddd d MMMM"

Background="backgrounds/vermilion.jpg"

AnimationDuration="300"
AnimationEasing="OutQuart"

DateTextColor="#e3beb9"
TimeTextColor="#f4ddd7"

InputFieldBackgroundColor="#66160d0d"
InputFieldTextColor="#f8e7e2"
PlaceholderTextColor="#bc8881"

LoginButtonTextColor="#120606"
LoginButtonBackgroundColor="#ef765c"

SystemButtonsIconsColor="#edc8c0"
EnvironmentButtonTextColor="#edc8c0"

DropdownTextColor="#f8e7e2"
DropdownBackgroundColor="#160d0d"
DropdownSelectedBackgroundColor="#d14436"

HoverLoginButtonBackgroundColor="#f5947e"
HoverSystemButtonsIconsColor="#f47a5c"
HoverEnvironmentButtonTextColor="#f47a5c"

Blur="0.12"
FormPosition="center"