[General]
Font="Plus Jakarta Sans"
FontSize="12"
HourFormat="HH:mm"
DateFormat="dddd d MMMM"

Background="wallpapers/malachite.jpg"

AnimationDuration="300"
AnimationEasing="OutQuart"

AutoFingerprintOnLoad=true

DateTextColor="#bdf5ef"
TimeTextColor="#eafffb"

FormBackgroundColor="#00140e"
LoginFieldBackgroundColor="#039687"
PasswordFieldBackgroundColor="#039687"

LoginFieldTextColor="#eafffb"
PasswordFieldTextColor="#eafffb"
PlaceholderTextColor="#7fbcb3"

LoginButtonTextColor="#00140e"
LoginButtonBackgroundColor="#009a93"

SystemButtonsIconsColor="#bdf5ef"
EnvironmentButtonTextColor="#bdf5ef"

DropdownTextColor="#bdf5ef"
DropdownSelectedTextColor="#00140e"
DropdownBackgroundColor="#001a12"
DropdownSelectedBackgroundColor="#009a93"
DropdownBorderColor="#016964"
DropdownSelectedBorderColor="#00a299"

HoverLoginButtonBackgroundColor="#19b3ae"
HoverSystemButtonsIconsColor="#19b3ae"
HoverEnvironmentButtonTextColor="#19b3ae"

Blur="0.05"
FormPosition="center"
