name: qml-lint

on:
  workflow_call:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    container:
      image: debian:trixie

    defaults:
      run:
        shell: bash

    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: base runner
        uses: ./.github/actions/base-runner

      - name: lint
        run: just l
