name: qml-format

on:
  workflow_call:

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest

    container:
      image: debian:trixie

    defaults:
      run:
        shell: bash

    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: base runner
        uses: ./.github/actions/base-runner

      - name: format check
        run: just f
